name: build_docker

on: push

jobs:
  build_dn42_bgp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dn42_bgp
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:bgp"
          platforms: linux/amd64,linux/arm64,linux/s390x,linux/arm/v7
          push: true
          tags: |
            runshine0819/dn42_bgp:latest
            ghcr.io/runshine/dn42_bgp:latest
          file: Dockerfile
          
  build_dn42_dns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dn42_dns
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:bind9"
          platforms: linux/amd64,linux/arm64,linux/s390x
          push: true
          tags: |
            runshine0819/dn42_dns:latest
            ghcr.io/runshine/dn42_dns:latest
          file: Dockerfile

  
